### PR TITLE
Only generate single contract bindings for ts

### PR DESCRIPTION
**Pull request by sergekh2**
+Remove versioning support from contract shims

### CODE REVIEW

**Comment by salzbrenner** [comment]
I have never had to use multiple versions, but it does seem like this could break something in the future. @giuseppecrj @tak-hntlabs wdyt?

**Comment by tak-hntlabs** [comment]
> I have never had to use multiple versions, but it does seem like this could break something in the future. @giuseppecrj @tak-hntlabs wdyt?

Serge, G and I are going to catch up tomorrow.

**Comment by texuf** [comment]
> > I have never had to use multiple versions, but it does seem like this could break something in the future. @giuseppecrj @tak-hntlabs wdyt?
> 
> Serge, G and I are going to catch up tomorrow.

The idea (correct me if I'm wrong) is that we will not break the current api of our diamond contracts, we will only add new apis and maybe tweak the underlying behavior of existing apis. 

If we ever export new ABIs and our code stops compiling, this should be a red flag.

If we add new features, we should add the ability to query the current contract and get back a feature set (Brian is going to build this right? :) )

**Review by texuf — APPROVED** [review]

**Comment by salzbrenner** [comment]
> If we ever export new ABIs and our code stops compiling, this should be a red flag.

Doesn't happen as often but still happens

**Comment by sergekh2** [comment]
we discussed it in the online meeting, in agreement to pick it up

**Pull request merged**
