### PR TITLE
Address gas estimate too low in tests when multiple test NFT are being minted in one block by incrementing the nonce properly

### PR DESCRIPTION
**Pull request by brianathere**
…

### CODE REVIEW

**Review by texuf — APPROVED** [review]
1) why is the test client re-using the same private key between transactions?
2) this won't prevent conflicts that are happening between node processes. I think by default the tests run 4 right?

**Comment by texuf** [comment]
did this cause the 
```
    TypeError: Do not know how to serialize a BigInt
        at stringify (<anonymous>)
```
or is that something else?

**Comment by brianathere** [comment]
> did this cause the
> 
> ```
>     TypeError: Do not know how to serialize a BigInt
>         at stringify (<anonymous>)
> ```
> 
> or is that something else?

I believe this change caused this, I'm now debugging locally.

**Comment by brianathere** [comment]
> 1. why is the test client re-using the same private key between transactions?
> 2. this won't prevent conflicts that are happening between node processes. I think by default the tests run 4 right?

I believe the client uses the default anvil test wallets when running, so it creating a test client uses the same wallet.

Excellent point about multi node, that is still a risk, but a smaller one.

Early on I had each node process creating a set of wallets to avoid that, using worker to generate them in parallel, but I believe you removed that and we defaulted back to the test wallets. I can look at re-introducing that, or using some form of nodeJS interprocess sharing to fix this, but for now I'll accept this risk.

This change addresses the coordinated race where a single test wants to mint multiple NFT all at once to test a multi NFT scenario.

**Comment by texuf** [comment]
> > 1. why is the test client re-using the same private key between transactions?
> > 2. this won't prevent conflicts that are happening between node processes. I think by default the tests run 4 right?
> 
> I believe the client uses the default anvil test wallets when running, so it creating a test client uses the same wallet.
> 
> Excellent point about multi node, that is still a risk, but a smaller one.
> 
> Early on I had each node process creating a set of wallets to avoid that, using worker to generate them in parallel, but I believe you removed that and we defaulted back to the test wallets. I can look at re-introducing that, or using some form of nodeJS interprocess sharing to fix this, but for now I'll accept this risk.
> 
> This change addresses the coordinated race where a single test wants to mint multiple NFT all at once to test a multi NFT scenario.

Instead of doing all this mutex stuff you can pass a privateKey to the "account" property of the createTextClient https://viem.sh/docs/clients/test.html#account-optional (I looked for this a month ago and couldn't find it) This convo helped.

**Comment by brianathere** [comment]
> > > 1. why is the test client re-using the same private key between transactions?
> > > 2. this won't prevent conflicts that are happening between node processes. I think by default the tests run 4 right?
> > 
> > 
> > I believe the client uses the default anvil test wallets when running, so it creating a test client uses the same wallet.
> > Excellent point about multi node, that is still a risk, but a smaller one.
> > Early on I had each node process creating a set of wallets to avoid that, using worker to generate them in parallel, but I believe you removed that and we defaulted back to the test wallets. I can look at re-introducing that, or using some form of nodeJS interprocess sharing to fix this, but for now I'll accept this risk.
> > This change addresses the coordinated race where a single test wants to mint multiple NFT all at once to test a multi NFT scenario.
> 
> Instead of doing all this mutex stuff you can pass a privateKey to the "account" property of the createTestClient https://viem.sh/docs/clients/test.html#account-optional (I looked for this a month ago and couldn't find it) This convo helped.

Creating private keys is expensive, though there's probably a way to make it fast. That's why I was doing it in parallel early on, it definitely goes faster with more CPU.

**Comment by texuf** [comment]
> > > > 1. why is the test client re-using the same private key between transactions?
> > > > 2. this won't prevent conflicts that are happening between node processes. I think by default the tests run 4 right?
> > > 
> > > 
> > > I believe the client uses the default anvil test wallets when running, so it creating a test client uses the same wallet.
> > > Excellent point about multi node, that is still a risk, but a smaller one.
> > > Early on I had each node process creating a set of wallets to avoid that, using worker to generate them in parallel, but I believe you removed that and we defaulted back to the test wallets. I can look at re-introducing that, or using some form of nodeJS interprocess sharing to fix this, but for now I'll accept this risk.
> > > This change addresses the coordinated race where a single test wants to mint multiple NFT all at once to test a multi NFT scenario.
> > 
> > 
> > Instead of doing all this mutex stuff you can pass a privateKey to the "account" property of the createTestClient https://viem.sh/docs/clients/test.html#account-optional (I looked for this a month ago and couldn't find it) This convo helped.
> 
> Creating private keys is expensive, though there's probably a way to make it fast. That's why I was doing it in parallel early on, it definitely goes faster with more CPU.

It’s test code that isn’t called very often and we’re already making multiple new ethers Wallet calls per user anyway, one more will not be a performance issue, and it will work across multiple processes

**Comment by brianathere** [comment]
> > > > > 1. why is the test client re-using the same private key between transactions?
> 
> > > > > 2. this won't prevent conflicts that are happening between node processes. I think by default the tests run 4 right?
> 
> > > > 
> 
> > > > 
> 
> > > > I believe the client uses the default anvil test wallets when running, so it creating a test client uses the same wallet.
> 
> > > > Excellent point about multi node, that is still a risk, but a smaller one.
> 
> > > > Early on I had each node process creating a set of wallets to avoid that, using worker to generate them in parallel, but I believe you removed that and we defaulted back to the test wallets. I can look at re-introducing that, or using some form of nodeJS interprocess sharing to fix this, but for now I'll accept this risk.
> 
> > > > This change addresses the coordinated race where a single test wants to mint multiple NFT all at once to test a multi NFT scenario.
> 
> > > 
> 
> > > 
> 
> > > Instead of doing all this mutex stuff you can pass a privateKey to the "account" property of the createTestClient https://viem.sh/docs/clients/test.html#account-optional (I looked for this a month ago and couldn't find it) This convo helped.
> 
> > 
> 
> > Creating private keys is expensive, though there's probably a way to make it fast. That's why I was doing it in parallel early on, it definitely goes faster with more CPU.
> 
> 
> 
> It’s test code that isn’t called very often and we’re already making multiple new ethers Wallet calls per user anyway, one more will not be a performance issue, and it will work across multiple processes

After finding more nonce issues, I'm convinced.

It kills me though how slow our tests are

**Pull request merged**
