### PR TITLE
Delete all facet addresses from the generated package

### PR DESCRIPTION
**Pull request by texuf**
We don’t and shouldn’t use these addresses, everything should be accessed through the diamonds. Keeping them up to date is a pain, so lets not have them at all.

Wrote a script that copies everything over and removes *facet.json files

### CODE REVIEW

**Review by jterzis — CHANGES_REQUESTED** [review]
Why are you deleting `space.json` corresponding to space diamond ? This will break diff reports, please don't delete this.

**Comment by texuf** [comment]
> Why are you deleting `space.json` corresponding to space diamond ? This will break diff reports, please don't delete this.

space.json is "an example space deployment" spaceFactory.json and spaceOwner are the diamonds

**Comment by jterzis** [comment]
> > Why are you deleting `space.json` corresponding to space diamond ? This will break diff reports, please don't delete this.
> 
> space.json is "an example space deployment" spaceFactory.json and spaceOwner are the diamonds

It's an example but also stores updated space facets which are canonical. We need this diamond to continue to exist so we can determine whether space facets differ between environments. If you remove the address, we won't be able to reference the corresponding deployed Space facets on alpha, gamma, omega.

**Comment by texuf** [comment]
> > > Why are you deleting `space.json` corresponding to space diamond ? This will break diff reports, please don't delete this.
> > 
> > 
> > space.json is "an example space deployment" spaceFactory.json and spaceOwner are the diamonds
> 
> It's an example but also stores updated space facets which are canonical. We need this diamond to continue to exist so we can determine whether space facets differ between environments. If you remove the address, we won't be able to reference the corresponding deployed Space facets on alpha, gamma, omega.

Thanks for the explanation, I'll add them back. @giuseppecrj ^^

**Comment by texuf** [comment]
> > > > Why are you deleting `space.json` corresponding to space diamond ? This will break diff reports, please don't delete this.
> > > 
> > > 
> > > space.json is "an example space deployment" spaceFactory.json and spaceOwner are the diamonds
> > 
> > 
> > It's an example but also stores updated space facets which are canonical. We need this diamond to continue to exist so we can determine whether space facets differ between environments. If you remove the address, we won't be able to reference the corresponding deployed Space facets on alpha, gamma, omega.
> 
> Thanks for the explanation, I'll add them back. @giuseppecrj ^^

But also - @jterzis - they are still, and will always be, in contracts/deployments... i'm only deleting them from generated/deployments, the package we publish to npm. Do we need them in both places? (okay if the answer is yes)

**Comment by texuf** [comment]
> > > > > Why are you deleting `space.json` corresponding to space diamond ? This will break diff reports, please don't delete this.
> > > > 
> > > > 
> > > > space.json is "an example space deployment" spaceFactory.json and spaceOwner are the diamonds
> > > 
> > > 
> > > It's an example but also stores updated space facets which are canonical. We need this diamond to continue to exist so we can determine whether space facets differ between environments. If you remove the address, we won't be able to reference the corresponding deployed Space facets on alpha, gamma, omega.
> > 
> > 
> > Thanks for the explanation, I'll add them back. @giuseppecrj ^^
> 
> But also - @jterzis - they are still, and will always be, in contracts/deployments... i'm only deleting them from generated/deployments, the package we publish to npm. Do we need them in both places? (okay if the answer is yes)

Ah one more thing, sorry for the never ending replies. Looks like you added a `Drop` class that references a `riverAirdrop` address... but you never hand copied those addresses into the generated/deployments folder so that will never work. @giuseppecrj here's one more. (looks like I approved your initial PR, sorry for not giving you better feedback John).

**Comment by jterzis** [comment]
> > > > > Why are you deleting `space.json` corresponding to space diamond ? This will break diff reports, please don't delete this.
> > > > 
> > > > 
> > > > space.json is "an example space deployment" spaceFactory.json and spaceOwner are the diamonds
> > > 
> > > 
> > > It's an example but also stores updated space facets which are canonical. We need this diamond to continue to exist so we can determine whether space facets differ between environments. If you remove the address, we won't be able to reference the corresponding deployed Space facets on alpha, gamma, omega.
> > 
> > 
> > Thanks for the explanation, I'll add them back. @giuseppecrj ^^
> 
> But also - @jterzis - they are still, and will always be, in contracts/deployments... i'm only deleting them from generated/deployments, the package we publish to npm. Do we need them in both places? (okay if the answer is yes)

@texuf we read them from contracts/deployments for diffing so it is okay I think to remove them from packages/generated.

**Comment by texuf** [comment]
updated this pr to only remove the facet.json files, also include a script to do the copying

**Pull request merged**
