### PR TITLE
perf(contract): Replace `Multicall` with Solady's `Multicallable`

### PR DESCRIPTION
**Pull request by shuhuiluo**
Removed internal `Multicall` implementation and interface. Updated references to use `Multicallable` from the Solady library for batch function calls. This optimizes and simplifies the contract dependencies.

### CODE REVIEW

**Comment by giuseppecrj** [comment]
Should we consider https://github.com/Vectorized/multicaller/blob/main/src/Multicaller.sol since this implementation is not payable aware

**Comment by shuhuiluo** [comment]
> Should we consider https://github.com/Vectorized/multicaller/blob/main/src/Multicaller.sol since this implementation is not payable aware

@giuseppecrj This one is a more general multicall for calling external contracts and not a drop-in replacement.

**Comment by shuhuiluo** [comment]
> should also add tests for how multicaller would be used in space proxy context.

There's no dedicated test contract for `SpaceProxy` but I added a fuzz test for multicall.

**Comment by giuseppecrj** [comment]
> > should also add tests for how multicaller would be used in space proxy context.
> 
> There's no dedicated test contract for `SpaceProxy` but I added a fuzz test for multicall.

the space proxy is an instance of a space, you can create test for it by inheriting BaseSetup and using either the `space` or `everyoneSpace` address since they're proxies

**Comment by shuhuiluo** [comment]
> > > should also add tests for how multicaller would be used in space proxy context.
> > 
> > 
> > There's no dedicated test contract for `SpaceProxy` but I added a fuzz test for multicall.
> 
> the space proxy is an instance of a space, you can create test for it by inheriting BaseSetup and using either the `space` or `everyoneSpace` address since they're proxies

@giuseppecrj Added.

**Review by giuseppecrj — APPROVED** [review]

**Pull request merged**
