### PR TITLE
refactor(sdk): refactor entitlement data ABI encoding and decoding

### PR DESCRIPTION
**Pull request by shuhuiluo**
As the title suggests.

### CODE REVIEW

**Comment by shuhuiluo** [comment]
@coderabbitai review

**Comment by shuhuiluo** [comment]
@coderabbitai full review

**Comment by shuhuiluo** [comment]
@coderabbitai full review

**Comment by shuhuiluo** [comment]
@coderabbitai full review

**Review by texuf — APPROVED** [review]

**Pull request merged**
