### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Budalebah**
pathway correction

### CODE REVIEW

**Review by sergekh2 — APPROVED** [review]

**Comment by Budalebah** [comment]
Can i join your channel in town?

**Comment by texuf** [comment]
> Can i join your channel in town?

Thank you for contributing to the River protocol. We are in the process of setting up a space for developers and we're talking about granting permissions or minting assets for contributors, but we haven't gotten around to that yet. Please subscribe to our twitter and be on the lookout for the new space https://x.com/buildonriver

**Comment by Budalebah** [comment]
already done thank you

**Comment by Budalebah** [comment]
Hey ser, anyway to contact you in telegram? I wanna build something and need to talk you

**Comment by texuf** [comment]
Come join our Friends of Towns town here: https://app.towns.com/t/10a78396e5860f3d4f8e020d40dbd753588f00e17d0000000000000000000000/

**Comment by Budalebah** [comment]
Done , thanks a lot

**Pull request merged**
