### PR TITLE
move sdk to vitest

### PR DESCRIPTION
**Pull request by miguel-nascimento**
I'm breaking #1462 into small PRs

Moving the sdk package from jest to vitest.

Why:
- modern: support ESM out of the box (jest requires ton of plugins and additional effort)
- no more `my-jest` and `--experimental-vm-modules`
- support for HMR - writing tests in watch mode works nice
- bit faster, easy for concurrent mode

Most changes of this PR includes: 

- `.toResolve()` -> `.resolves.not.toThrow()`
- `.toReject()` -> `.rejects.toThrow()`
- `.toBeTrue()` -> `.toBe(true)`
- `.toBeFalse()` -> `.toBe(false)`
- `jsdom` -> `happy-dom`

### CODE REVIEW

**Comment by texuf** [comment]
are you sure these tests are passing, the multinode_ent all have error messages and yellow checks. Is a yellow check a pass?
```
   ✓ member.test.ts - queue update > queue update metadata 4247ms
stderr | src/sync-agent/spaces/spaces.test.multi.ts > spaces.test.ts > create/leave/join space
AggregateError: 
    at internalConnectMultiple (node:net:1118:18)
    at afterConnectMultiple (node:net:1685:7) {
  code: 'ECONNREFUSED',
  [errors]: [
    Error: connect ECONNREFUSED ::1:3000
        at createConnectionError (node:net:1648:14)
        at afterConnectMultiple (node:net:1678:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 3000
    },
    Error: connect ECONNREFUSED 127.0.0.1:3000
        at createConnectionError (node:net:1648:14)
        at afterConnectMultiple (node:net:1678:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 3000
    }
  ]
}
```

**Comment by texuf** [comment]
looks like vitest just prints errors and warnings, probably a good thing! we should fix errors and warnings. Did you confirm that the number of tests executed is the same as a non vitest pr?
i.e.:
```
Test Files  35 passed | 1 skipped (36)
      Tests  178 passed | 2 skipped (180)
```

**Comment by texuf** [comment]
@sergekh2 suggested the folder option for tests. I'm actually fine with it if we just put a tests folder so that it's `tests/<unit/multi/multi_ne/multi_v2>` etc... i think that makes way more sense.

**Comment by miguel-nascimento** [comment]
**Multinode > Run SDK Tests (without entitlements)**

Jest
```
Test Suites: 42 passed, 42 of 71 total
Tests:       1 skipped, 190 passed, 191 total
Snapshots:   0 total
Time:        443.342 s
Ran all test suites.
```

Vitest:
```
 Test Files  35 passed | 1 skipped (36)
      Tests  178 passed | 2 skipped (180)
   Start at  22:30:00
   Duration  168.93s (transform 1.85s, setup 1.21s, collect 36.05s, tests 843.55s, environment 12.01s, prepare 2.87s)
```
There are 7 tests suite missing 

**Multinode Ent > Run SDK Tests (with entitlements)**

Jest
```
Test Suites: 23 passed, 23 of 71 total
Tests:       123 passed, 123 total
Snapshots:   0 total
Time:        1085.794 s
```

Vitest
```
 Test Files  25 passed (25)
      Tests  130 passed (130)
   Start at  22:32:49
   Duration  774.43s (transform 1.82s, setup 727ms, collect 27.61s, tests 1744.49s, environment 7.95s, prepare 1.68s)
```

I'll check what are the tests that vitest is running ahead.


**Multinode Ent Legacy > Run River Tests against Legacy Spaces**

Jest
```
Test Suites: 20 passed, 20 of 71 total
Tests:       104 passed, 104 total
Snapshots:   0 total
Time:        1068.463 s
```

Vitest
```
 Test Files  22 passed (22)
      Tests  111 passed (111)
   Start at  22:32:58
   Duration  773.21s (transform 1.94s, setup 772ms, collect 27.66s, tests 1417.47s, environment 7.37s, prepare 1.65s)
```

I'll check what are the tests that vitest is running ahead.

**Comment by miguel-nascimento** [comment]
I think that with the current structure of tests being in the same folder and being called `<filename>.test.ts`, if we move tests to a dedicated folder, it will break the structure, tests will be far from the original implementation.

I'm not happy with `<filename>.test.<env>.ts`, I think the `describe('<env>/...')` is a better solution here, it will keep filenames clean and tests close to the implementation. 

What do you think?

**Pull request merged**
