### PR TITLE
Update checksum for eth-infinitism/account-abstraction

### LINKED ISSUE #597: `yarn install --immutable` fails on a fresh checkout due to `account-abstraction` hash mismatch.
**Describe the bug**

`yarn install --immutable` fails on a fresh checkout of the repository on a new system due to dependency resolution errors.

the most important one seems to be

```
➤ YN0018: │ account-abstraction@https://github.com/eth-infinitism/account-abstraction.git#commit=7af70c8993a6f42973f520ae0752386a5032abe7: The remote archive doesn't match the expected checksum
```

Which seems to be caused by a wrong checksum for `eth-infinitism/account-abstraction` in the `yarn.lock` file.

**To Reproduce**

On a fresh system (without any prior installations of dependencies)

```bash
$ git clone git@github.com:river-build/river.git
$ cd river
$ yarn install --immutable
(...)
➤ YN0000: Failed with errors in 1m 5s
```

**Expected behavior**

`yarn install --immutable` should install all the dependencies.

**Screenshots**

N/A.

**Desktop (please complete the following information):**

- OS: `macOS Sonoma 14.5`
- Processor: `Apple M2 Pro`
- Browser `N/A`
- Version `N/A`

In addition
- nodejs `20.16.0`
- yarn `3.8.0`

**Logs**

Here is the detailed console output

```bash
$ yarn install --immutable
➤ YN0000: ┌ Project validation
➤ YN0057: │ @river-build/sdk: Resolutions field will be ignored
➤ YN0057: │ @river-build/stress: Resolutions field will be ignored
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @nrwl/devkit@npm:19.3.1 doesn't provide nx (p26e93), requested by @nx/devkit
➤ YN0002: │ @river-build/dlog@workspace:packages/dlog doesn't provide @types/node (p43716), requested by ts-node
➤ YN0060: │ @river-build/dlog@workspace:packages/dlog provides @typescript-eslint/parser (pb726c) with version 7.14.1, which doesn't satisfy what @typescript-eslint/eslint-plugin requests
➤ YN0060: │ @river-build/dlog@workspace:packages/dlog provides eslint (p46f9d) with version 8.53.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0060: │ @river-build/encryption@workspace:packages/encryption provides @typescript-eslint/parser (p5c251) with version 7.14.1, which doesn't satisfy what @typescript-eslint/eslint-plugin requests
➤ YN0060: │ @river-build/encryption@workspace:packages/encryption provides eslint (pdecae) with version 8.53.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0060: │ @river-build/playground@workspace:packages/playground provides @typescript-eslint/parser (p8297a) with version 7.14.1, which doesn't satisfy what @typescript-eslint/eslint-plugin requests
➤ YN0060: │ @river-build/playground@workspace:packages/playground provides eslint (p7c502) with version 8.53.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0060: │ @river-build/react-sdk@workspace:packages/react-sdk provides @typescript-eslint/parser (p7e4a2) with version 7.14.1, which doesn't satisfy what @typescript-eslint/eslint-plugin requests
➤ YN0060: │ @river-build/react-sdk@workspace:packages/react-sdk provides eslint (p554c0) with version 8.53.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0060: │ @river-build/react-sdk@workspace:packages/react-sdk [12e8a] provides @typescript-eslint/parser (p1b094) with version 7.14.1, which doesn't satisfy what @typescript-eslint/eslint-plugin requests
➤ YN0060: │ @river-build/react-sdk@workspace:packages/react-sdk [12e8a] provides eslint (p73e73) with version 8.53.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0060: │ @river-build/sdk@workspace:packages/sdk provides @typescript-eslint/parser (p58a43) with version 7.14.1, which doesn't satisfy what @typescript-eslint/eslint-plugin requests
➤ YN0060: │ @river-build/sdk@workspace:packages/sdk provides eslint (p9b7e3) with version 8.53.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0002: │ @river-build/sdk@workspace:packages/sdk doesn't provide jest-docblock (pfddd0), requested by jest-runner-groups
➤ YN0002: │ @river-build/sdk@workspace:packages/sdk doesn't provide jest-runner (pbfd14), requested by jest-runner-groups
➤ YN0002: │ @river-build/sdk@workspace:packages/sdk doesn't provide react (pb2242), requested by @testing-library/react
➤ YN0002: │ @river-build/sdk@workspace:packages/sdk doesn't provide react-dom (p5a5d4), requested by @testing-library/react
➤ YN0002: │ @river-build/stress@workspace:packages/stress doesn't provide @babel/core (pb2377), requested by @babel/node
➤ YN0060: │ @river-build/stress@workspace:packages/stress provides @typescript-eslint/parser (p18af1) with version 7.14.1, which doesn't satisfy what @typescript-eslint/eslint-plugin requests
➤ YN0060: │ @river-build/stress@workspace:packages/stress provides eslint (p53eaf) with version 8.53.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0002: │ @river-build/stress@workspace:packages/stress doesn't provide jest-docblock (p9bc9b), requested by jest-runner-groups
➤ YN0002: │ @river-build/stress@workspace:packages/stress doesn't provide jest-runner (p7965e), requested by jest-runner-groups
➤ YN0002: │ @river-build/stress@workspace:packages/stress doesn't provide react (pe1475), requested by @testing-library/react
➤ YN0002: │ @river-build/stress@workspace:packages/stress doesn't provide react-dom (pbd860), requested by @testing-library/react
➤ YN0060: │ @river-build/web3@workspace:packages/web3 provides @typescript-eslint/parser (pecae5) with version 7.14.1, which doesn't satisfy what @typescript-eslint/eslint-plugin requests
➤ YN0060: │ @river-build/web3@workspace:packages/web3 provides eslint (pf8297) with version 8.53.0, which doesn't satisfy what @typescript-eslint/parser requests
➤ YN0002: │ account-abstraction@https://github.com/eth-infinitism/account-abstraction.git#commit=7af70c8993a6f42973f520ae0752386a5032abe7 doesn't provide ethers (p2f81d), requested by hardhat-deploy-ethers
➤ YN0002: │ account-abstraction@https://github.com/eth-infinitism/account-abstraction.git#commit=7af70c8993a6f42973f520ae0752386a5032abe7 doesn't provide hardhat (pa60a6), requested by @nomiclabs/hardhat-etherscan
➤ YN0002: │ account-abstraction@https://github.com/eth-infinitism/account-abstraction.git#commit=7af70c8993a6f42973f520ae0752386a5032abe7 doesn't provide hardhat (p59042), requested by @typechain/hardhat
➤ YN0002: │ account-abstraction@https://github.com/eth-infinitism/account-abstraction.git#commit=7af70c8993a6f42973f520ae0752386a5032abe7 doesn't provide hardhat (p589c8), requested by hardhat-deploy-ethers
➤ YN0002: │ account-abstraction@https://github.com/eth-infinitism/account-abstraction.git#commit=7af70c8993a6f42973f520ae0752386a5032abe7 doesn't provide hardhat (pef8a5), requested by solidity-coverage
➤ YN0002: │ account-abstraction@https://github.com/eth-infinitism/account-abstraction.git#commit=7af70c8993a6f42973f520ae0752386a5032abe7 doesn't provide lodash (pa13d2), requested by @typechain/hardhat
➤ YN0002: │ account-abstraction@https://github.com/eth-infinitism/account-abstraction.git#commit=7af70c8993a6f42973f520ae0752386a5032abe7 doesn't provide typechain (p544cf), requested by @typechain/hardhat
➤ YN0002: │ river-build@workspace:. doesn't provide @ethersproject/abi (pa9116), requested by @typechain/ethers-v5
➤ YN0002: │ river-build@workspace:. doesn't provide @ethersproject/bytes (p3ccbc), requested by @typechain/ethers-v5
➤ YN0002: │ river-build@workspace:. doesn't provide @ethersproject/providers (p98061), requested by @typechain/ethers-v5
➤ YN0002: │ river-build@workspace:. doesn't provide ethers (p68744), requested by @typechain/ethers-v5
➤ YN0002: │ river-build@workspace:. doesn't provide hardhat (pac429), requested by solidity-docgen
➤ YN0002: │ ts-command-line-args@npm:2.4.2 doesn't provide typescript (p05d79), requested by @morgan-stanley/ts-mocking-bird
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 207ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:1.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zksync-web3@npm:0.14.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:3.22.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zustand@npm:4.5.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A5.5.2#~builtin<compat/typescript>::version=5.5.2&hash=d69c25: Cannot apply hunk #1
➤ YN0013: │ account-abstraction@https://github.com/eth-infinitism/account-abstraction.git#commit=7af70c8993a6f42973f520ae0752386a5032abe7 can't be found in the cache and will be fetched from the remote repo
➤ YN0018: │ account-abstraction@https://github.com/eth-infinitism/account-abstraction.git#commit=7af70c8993a6f42973f520ae0752386a5032abe7: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 1m 5s
➤ YN0000: Failed with errors in 1m 5s
```

**Additional context**
The following diff seems to resolve the issue.  However, it is unclear why this issue has not been picked up by the CI.

```diff
diff --git a/yarn.lock b/yarn.lock
index 9b305f9..b49da0d 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -5904,7 +5904,7 @@ __metadata:
     source-map-support: ^0.5.19
     table: ^6.8.0
     typescript: ^4.3.5
-  checksum: bdca754160deb9b34a6b668bbcb80477c1c596cdaa90ed4966e0b557f32d26f1d973033a468dca016ad8e5d909c68f15859408208b70602bdee0619c6208bd02
+  checksum: 7a95ae91ba600beaa22ce7f5ab09003fb9eccf3e56e38e3b0d1a36dd8a07ae581eeedd939f90ce6e9ef3a189fcad746228ba2703331964b398acf6437dc0e54b
   languageName: node
   linkType: hard
 ```

### PR DESCRIPTION
**Pull request by jakzale**
Closes #597

### CODE REVIEW

**Comment by jakzale** [comment]
This commit works on my machine, but it _should_ break the CI, due to a different version of `eth-infinitism/account-abstraction` being cached by GitHub Actions.  If it doesn't, then there is something weird going on with that particular package.

**Comment by texuf** [comment]
Sorry it took so long to kick this off. Hypothesis confirmed. It breaks CI. I wonder what's going on on your machine.

**Comment by brianathere** [comment]
Theory is either how he installed yarn (core), or he has some .yarn configuration in his home directory. John saw something like this last year, we think it was core

**Comment by jakzale** [comment]
Closing this now.  I was able to succeed in a fresh macOS VM, and then I was able to succeed by nuking my old setup and switching to `nvm`.  Detailed steps mentioned in #597.

**Pull request closed without merging**
